#!/bin/bash

# We can use pacman if the system is arch based
if test -f /etc/arch-release; then
	echo "[Bootstrap] Remove all cached packages"
	sudo pacman -Sc

	echo "[Bootstrap] Sync and update all packages first"
	sudo pacman -Syu

	echo "[Bootstrap] Downloading packages.."
	sudo pacman -Syy neovim tmux alacritty fish starship exa bat gnupg
	
	# Install nodejs and xclip that are required to:
	# nodejs: use coc (vs-code like autocompletions)
	# xclip: copy + paste functionalities in nvim
	echo "[Bootstrap] Install nvim dependencies"
	sudo pacman -Syy nodejs xclip

	# Make Fish the default shell
	echo "[Boostrap] Configuring Fish as deault shell"
	printf "\n/usr/bin/fish" >> /etc/shells
	chsh -s /usr/bin/fish
	
	# Install Rustup
	# The official and recommended method of installing Rust for the purpose of 
	# developing software is to use the Rustup toolchain manager, written in Rust. 
	echo "[Boostrap] Installing Rustup"
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rust.sh
	chmod +x ./rust.sh
	./rust.sh

	echo "[Boostrap - Rustup Installation] Installing rust toolchain components"
	rustup component add rls rust-analysis rust-src
fi
