#!/bin/bash

echo "[Bootstrap] Downloading packages.."
sudo pacman -Syy neovim tmux alacritty fish starship exa bat gnupg

echo "[Bootstrap] Install nvim dep."
sudo pacman -Syy nodejs

# Make Fish the default shell
echo "[Boostrap] Configuring Fish as deault shell"
printf "\n/usr/bin/fish" >> /etc/shells
chsh -s /usr/bin/fish
